### ISSUE TITLE
Feature Idea - Type Restricted Getters and Setters

### ISSUE THREAD

**Issue by dsherret** [mikkoh/jsOOP#1]
It would be a neat idea to have an easy way to create type restricted and instance restricted getters and setters. What do you think?

**Comment by mikkoh** [comment]
I've actually debated about the amount of type checking that should happen. I was thinking of removing the type checking entirely. Have to think about it.

**Comment by dsherret** [comment]
Why remove it when it would be optional? If people don't want type checking, then they don't have to use it. I think it would be useful in some cases.

**Comment by dsherret** [comment]
I was thinking about this more and I would agree that type checking shouldn't be done. It should instead be checked manually by the user. 

By the way, the syntax for checking instanceof would be a bit awkward. Probably would have to do something like this:

``` javascript
myProp: {
    get: function() {
        return this._prop;
    },
    set: function( value ) {
        this._prop = value;
    },
    instance: function(val) { return val instanceof MyClass; }
  },
```

That just looks bad. They could instead manually do type or instance checking within the set function.

**Comment by mikkoh** [comment]
Yeah the more I've been working on this there more I've felt that type checking stuff would be bad. Although it could still be implemented "optionally".
